apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: Vyshnavinerella25/back
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: db
        - name: DB_NAME
          value: microservices_db
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: password
